// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import PlayerController from "./player_controller.js"
application.register("player", PlayerController)