development:
  version: 0.1
  dict:
    雅思王语料库第11章Section1: /materials/ysw_c11_s1.txt
    雅思王语料库第12章Section2: /materials/ysw_c11_s2.txt


production:
  version: 0.1
  dict:
    雅思王语料库第11章Section1: /materials/ysw_c11_s1.txt
    雅思王语料库第12章Section2: /materials/ysw_c11_s2.txt